### ISSUE TITLE
Грешен пример

### ISSUE THREAD

**Issue by nikolaystanishev** [HackBulgaria/ApplicationFall2016#3]
На задача Heads and Tails последния пример е згрешен:
Input: T, T, T, H, T, T, T, H, T, T, T, H, H, H, H
Output: H wins!
а трябва да бъде:
Input: T, T, T, H, T, T, T, H, T, T, T, H, H, H, H
Output: T wins!

**Comment by YavorGIvanov** [comment]
After n tosses, the winner is the one who has the longest **consecutive** win-streak. 
Пропускаш това, че става въпрос за най-голям брой **последователни** хвърляния, а не попринцип.

**Comment by pgergov** [comment]
@nikolaystanishev ключовото в условието на задачата е `longest consecutive win-streak`.
Успех!
